version: "3.10"

services:

  worker:

    build: .

    environment:

      API_HASH: $API_HASH

      API_ID: $API_ID

      BOT_TOKEN: $BOT_TOKEN

      OWNER_ID: $OWNER_ID

      MONGODB_URI: $MONGODB_URI

      LOG_CHANNEL: $LOG_CHANNEL

      DOWNLOAD_DIR: $DOWNLOAD_DIR

      BROADCAST_AS_COPY: $BROADCAST_AS_COPY
